services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: recipes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d recipes_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  fastapi:
    build: .
    ports:
      - "8000:80"  # Изменили с 80:80 на 8000:80
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://app_user:app_password@postgres:5432/recipes_db
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 80"

volumes:
  postgres_data: